apiVersion: v1
kind: Service

metadata:
  name: aorax-service

spec:
  type: NodePort

  selector:
    app: aorax

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500